name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [workflow_dispatch]
jobs:
  Check-Out:
    runs-on: self-hosted
    environment: 
      name: staging
      #url: file:///home/githubactions/actions-runner/_work/GitHubActionsDemo/GitHubActionsDemo/main
      url: ${{ github.workspace }}/${{ github.ref_name }}
    steps:    
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: main
  SonarQube-Scan:
    runs-on: self-hosted
    environment:
      name: staging
      url: http://10.0.2.15:9000/dashboard?id=GitHubActions-Demo
    needs: Check-Out
    steps: 
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with: 
          projectBaseDir: ${{ github.workspace }}/${{ github.ref_name }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}   
      - name: Open SonarQube Page
        run: xdg-open http://10.0.2.15:9000/dashboard?id=GitHubActions-Demo
  Docker-Build-Push:
    runs-on: self-hosted
    needs: SonarQube-Scan
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: arndvorrath/githubactionsdemo:latest
      - name: Open DockerHub page
        run: xdg-open https://hub.docker.com/repository/docker/arndvorrath/githubactionsdemo/general
  Docker-Deploy:
    runs-on: self-hosted
    needs: Docker-Build-Push 
    steps:
      - name: Docker Deploy
        run: docker run -p 49160:8080 -d arndvorrath/githubactionsdemo:latest
      - name: Open HelloWorld page
        run: xdg-open http://10.0.2.15:49160
   

