name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [workflow_dispatch]
jobs:
  Check-Out:
    name: Check out repository code
    runs-on: self-hosted
    steps:    
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: main
  SonarQube-Scan:
    name: Execute SonarQube Scan
    runs-on: self-hosted
    needs: Check-Out
    environment:
      name: staging
      url: http://10.0.2.15:9000/dashboard?id=GitHubActions-Demo
    steps: 
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with: 
          projectBaseDir: ${{ github.workspace }}/${{ github.ref_name }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} 
  SonarQube-Show:
    name: Show SonarQube Report
    runs-on: self-hosted
    needs: SonarQube-Scan
    steps:
      - name: Open SonarQube Page
        run: |
          # xdg-open http://10.0.2.15:9000/dashboard?id=GitHubActions-Demo
          export DISPLAY=':0'
          firefox http://10.0.2.15:9000/dashboard?id=GitHubActions-Demo
  Docker-Build-Push: 
    name: Build & Push Docker Image
    runs-on: self-hosted
    needs: [SonarQube-Scan]
    environment:
      name: staging
      url: https://hub.docker.com/repository/docker/arndvorrath/githubactionsdemo/general
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: arndvorrath/githubactionsdemo:latest
  DockerHub-Show: 
    name: Show DockerHub Repository
    runs-on: self-hosted
    needs: [Docker-Build-Push] 
    steps:
      - name: Open DockerHub page
        run: xdg-open https://hub.docker.com/repository/docker/arndvorrath/githubactionsdemo/general
  Docker-Deploy:
    name: Deploy new Docker container
    runs-on: self-hosted
    needs: [Docker-Build-Push]
    environment:
      name: staging
      url: http://10.0.2.15:49160
    steps:
      - name: Stop old Docker container
        run: docker stop $(docker ps -a -q)
      - name: Deploy new Docker container
        run: docker run -p 49160:8080 -d arndvorrath/githubactionsdemo:latest
  Selenium-Test:
    name: Execute Selenium Cucumber tests
    runs-on: self-hosted
    needs: [Docker-Deploy] 
    steps:
      - name: Execute Selenium Cucumber test
        run: |
          cd main
          mvn verify
  Selenium-Show:
    name: Show Cucumber Report
    runs-on: self-hosted
    needs: [Selenium-Test] 
    steps:
      - name: Show Cucumber report
        run: xdg-open /home/githubactions/actions-runner/_work/GitHubActionsDemo/GitHubActionsDemo/main/target/cucumber-html-reports/overview-features.html    
  Xray-Upload:
    name: Upload Report in Xray
    runs-on: self-hosted
    needs: [Selenium-Test] 
    steps:
      - name: Upload Report in Xray     
        uses: dedene/curl@v1
        with:
          args: -H "Content-Type:application/json" -X POST -H "Authorization:Bearer NzQ3ODI1NzE4NTg3OtuwGrJJJWBd1fg2oXpcSQi9YmFg" --data @/home/githubactions/actions-runner/_work/GitHubActionsDemo/GitHubActionsDemo/main/target/cucumber.json "https://proactioneu.ent.cgi.com/jira/rest/raven/1.0/import/execution"
  Mail-Send:
    name: Send a Notification email
    runs-on: self-hosted
    needs: [Selenium-Test]
    steps:   
      - name: Announcerr
        uses: singhkshitij/announcerr@v2.0
        with:
          server_address: smtp-mail.outlook.com
          server_port: 587
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Launching my awesomeProduct version ${{ github.event.release.tag_name }}
          # Literal body:
          # body: Just launched new version of my ${{github.repository}} ! It is fully packed with awesome features.
          # Read file contents as body:
          body: file:///home/githubactions/actions-runner/_work/GitHubActionsDemo/GitHubActionsDemo/main/target/cucumber-html-reports/overview-features.html 
          to: qammeister@gmail.com
          from: GitHub-Actions-Demo # <qammeister@gmail.com>
          # Optional content type (defaults to text/plain):
          content_type: text/html
          # Optional attachments:
          attachments: /home/githubactions/actions-runner/_work/GitHubActionsDemo/GitHubActionsDemo/main/target/cucumber-html-reports/overview-features.html 
  Show-Mail:
    name: Show Notification Mail
    runs-on: self-hosted
    needs: [Mail-Send] 
    steps:
      - name: Show Notification Mail
        run: xdg-open https://mail.google.com/mail/u/0/#inbox 

