name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    container: null
    # runs-on: ubuntu-latest
    steps:    
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: main
      - name: SonarQube Scan
      #  uses: sonarsource/sonarqube-scan-action@master
        uses: sonarsource/sonarcloud-github-action@master
      #  env:
        with:
      #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
      #    SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  
          login: ${{ secrets.SONAR_TOKEN }} 
          host: ${{ secrets.SONAR_HOST_URL }}       
      #- name: Set up QEMU
      #  uses: docker/setup-qemu-action@v3
      #- name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v3
      #  with:
      #    driver-opts: network=host
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          registry: docker.io
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      - name: Build and push
#        uses: docker/build-push-action@v5
#        with:
#          push: true
#          tags: arndvorrath/githubactionsdemo:latest
   

