name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [workflow_dispatch]
jobs:
  Check-Out:
    name: Check out repository code
    runs-on: self-hosted
    steps:    
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: main
  SonarQube-Scan:
    name: Execute SonarQube Scan
    runs-on: self-hosted
    needs: Check-Out
    steps: 
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with: 
          projectBaseDir: ${{ github.workspace }}/${{ github.ref_name }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} 
  SonarQube-Show:
    name: Show SonarQube Report
    runs-on: self-hosted
    needs: SonarQube-Scan
    steps:
      - name: Open SonarQube Page
        run: xdg-open http://10.0.2.15:9000/dashboard?id=GitHubActions-Demo
  DockerHub-Login:
    name: Login to DockerHub
    runs-on: self-hosted
    needs: [SonarQube-Scan] 
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  Docker-Build-Push: 
      name: Build and Push Docker Image
      runs-on: self-hosted
      needs: [SonarQube-Scan,DockerHub-Login] 
      steps:
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: arndvorrath/githubactionsdemo:latest
  Open-DockerHub: 
      name: Open DockerHub Repository
      runs-on: self-hosted
      needs: [Docker-Build-Push] 
      steps:
      - name: Open DockerHub page
        run: xdg-open https://hub.docker.com/repository/docker/arndvorrath/githubactionsdemo/general
  Docker-Housekeeping:
        name: Stop old Docker container
        runs-on: self-hosted
        needs: [Docker-Build-Push]
        steps:
        - name: Docker stop running containers
          run: docker stop $(docker ps -a -q)
  Docker-Deploy:
        name: Deploy new Docker container
        runs-on: self-hosted
        needs: [Docker-Housekeeping]      
        environment:
         name: staging
         url: http://10.0.2.15:49160
        steps:
         - name: Docker Deploy
           run: docker run -p 49160:8080 -d arndvorrath/githubactionsdemo:latest
  #Open-HelloCGI-Page:
  #      name: Open 'Hello CGI' page
  #      runs-on: self-hosted
  #      needs: Docker-Deploy
  #      steps:
  #      - name: Open 'Hello CGI' page
  #        run: xdg-open http://10.0.2.15:49160

