name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:    
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: main
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with: 
          projectBaseDir: /home/githubactions/actions-runner/_work/GitHubActionsDemo/GitHubActionsDemo/main
          #projectBaseDir: ${{ env.GITHUB_WORKSPACE }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
          # SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}   
          SONAR_HOST_URL: http://10.0.2.15:9000  
      - name: Open SonarQube Page
        run: xdg-open http://10.0.2.15:9000/dashboard?id=GitHubActions-Demo
      #- name: Set up QEMU
      #  uses: docker/setup-qemu-action@v3
      #- name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v3
      #  with:
      #    driver-opts: network=host
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: arndvorrath/githubactionsdemo:latest
   

